export const DAMAGE_TYPES = [
    "Fisura longitudinal en vigas",
    "Fisura diagonal por cortante",
    "Fisuración en nodos",
    "Desprendimiento de recubrimiento",
    "Corrosión de armaduras expuestas",
    "Pandeo local en perfiles",
    "Deformación excesiva de losas",
    "Asentamiento diferencial",
    "Delaminación en elementos de hormigón",
    "Aplastamiento en apoyos",
    "Grieta vertical en muros",
    "Humedad capilar y eflorescencias",
    "Fallo o fisura en soldaduras",
    "Aflojamiento o pérdida de pernos",
    "Erosión o socavación en fundaciones",
    "Impacto localizado en elementos",
    "Fatiga en elementos metálicos",
    "Rotura o pérdida de arriostramientos",
    "Pérdida de sección por corrosión generalizada",
    "Desalineación o desplazamiento de marcos",
];
export const DAMAGE_CAUSES = [
    "Sobrecarga gravitacional sostenida",
    "Sobrecarga accidental o impacto",
    "Deficiencias de diseño estructural",
    "Detalles constructivos deficientes",
    "Curado inadecuado del hormigón",
    "Corrosión inducida por cloruros",
    "Carbonatación avanzada",
    "Humedad permanente o fugas",
    "Movimiento sísmico recurrente",
    "Vibraciones por maquinaria",
    "Cambio de uso no evaluado",
    "Fatiga por cargas cíclicas",
    "Incendio o acción térmica",
    "Asentamiento del terreno",
    "Socavación por agua subterránea",
    "Impacto vehicular",
    "Choque de equipos móviles",
    "Errores de mantenimiento",
    "Compatibilidad deficiente de materiales",
    "Corrosión galvánica",
];
export const DAMAGE_SEVERITIES = ["Leve", "Media", "Alta", "Muy Alta"];
